services:
  php:
    image: tugboatqa/php:7.4-apache
    default: true
    depends:
      - mysql
    commands:
      update: |
        set -eux
        export COMPOSER_MEMORY_LIMIT=-1
        ln -snf $TUGBOAT_ROOT/.tugboat/drupal/web $DOCROOT
        cd .tugboat/drupal
        composer install --optimize-autoloader
        composer config repositories.tugboat vcs $TUGBOAT_ROOT
        composer require drupal/graphql:dev-tugboat
        # Not sure if this is a GraphQL quirk, but I needed to explicitly
        # require this dependency.
        composer require drupal/typed_data
        vendor/bin/drush --yes --db-url=mysql://tugboat:tugboat@mysql:3306/tugboat site:install standard
        vendor/bin/drush --yes en graphql
      build: |
        set -eux
        export COMPOSER_MEMORY_LIMIT=-1
        cd .tugboat/drupal
        composer install --optimize-autoloader
        composer update drupal/graphql --with-all-dependencies
        vendor/bin/drush --yes updb
        vendor/bin/drush cache:rebuild
  mysql:
    image: tugboatqa/percona:5.6
    commands:
      init:
        - printf '[mysqld]\ninnodb_log_file_size = 50331648\nmax_allowed_packet = 128M\n' > /etc/my.cnf.d/zzz.cnf
        - sv restart percona

